### ISSUE TITLE
Remote Mining Improvements

### ISSUE THREAD

**Issue by lipkam** [justonhart/Thoughtwave#108]
- Bigger reservers: Spawn only when low reserve in remote room to save on cpu
- Kill gatherers on containers if travelCost to their targetSource is more than twice the time left to live (renewing makes no sense since it costs the same and takes just as long to completely renew the creep - bigger body creeps get less time renewed per action)
- Improvement for gatherers to use roomData road happens in separate issue

**Comment by justonhart** [comment]
Redesign calculates the number of gatherers theoretically required per source to get 100% efficiency. Need to find a way to get gatherers to time their trips efficiently
